### ISSUE TITLE
demo 运行后，首页 进去啥都看不到

### ISSUE THREAD

**Issue by jiaforios** [yangyangFeng/TTPatch#11]
demo 不友好啊

**Comment by yangyangFeng** [comment]
![image](https://user-images.githubusercontent.com/12904185/78109505-e73a6100-742b-11ea-945e-2b9f6b56f5a3.png)
首页没显示吗?
加群: 978337686 交流一下

**Comment by yangyangFeng** [comment]
目前只支持模拟器实时预览,手机需要将outputs资源文件拖到工程中以bundle方式加载

**Comment by yangyangFeng** [comment]
> demo 不友好啊

demo是随手写的....欢迎发表意见, 我尽量改的友好点.
