### ISSUE TITLE
怎么Demo中的Block调用直接闪退，模拟器和真机都闪退

### ISSUE THREAD

**Issue by moxcomic** [yangyangFeng/TTPatch#18]

**Comment by yangyangFeng** [comment]
是直接在demo中运行吗? 请问系统版本是多少.

**Comment by yangyangFeng** [comment]
已修复

**Comment by HebeTienCoder** [comment]
webView_decidePolicyForNavigationAction_decisionHandler_:dynamic(',id,id,?',function(webView, navigationAction, 
decisionHandler) {
    //手动设置签名
    decisionHandler(block(',int'),1);
}),

参照文档写的，还是闪退

**Comment by yangyangFeng** [comment]
> webView_decidePolicyForNavigationAction_decisionHandler_:dynamic(',id,id,?',function(webView, navigationAction,
> decisionHandler) {
> //手动设置签名
> decisionHandler(block(',int'),1);
> }),
> 
> 参照文档写的，还是闪退

`decisionHandler(block(',int'),1);`
 修改为 
`decisionHandler(block("void,int"), 1);`
由于底层逻辑修改, 将签名默认返回值void 改为 默认返回值id, 所以返回值为void是,需显示标明
