### ISSUE TITLE
自定义UIView，在使用TTPatch更新自定义属性setter方法里使用setValue:forKey:方法，会报UIView找不到undifineKey 这个会是什么原因呢？

### ISSUE THREAD

**Issue by LuoPengFei** [yangyangFeng/TTPatch#20]
Fatal Exception: NSUnknownKeyException
[<UIView 0x13f689e50> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key _minValue

转义后代码：
defineClass('TBSliderView', {setMaxValue_: function (maxValue) { self._c('setValue_forKey_', maxValue, '_maxValue'); if (isNaN(maxValue)) { var value = self._c('valueForKey_', '_value'); self._c('setValue_forKey_', value,'_maxValue');}var max = self._c('valueForKey_', '_maxValue');self._c('customSlider')._c('setMaximumValue_', max);var callback = self._c('valueFormatter');if (callback) {self._c('maxValueLabel')._c('setText_', callback(max));}},setMinValue_: function (minValue) {self._c('setValue_forKey_', minValue, '_minValue');if (isNaN(minValue)) {var value = self._c('valueForKey_', '_value');self._c('setValue_forKey_', value, '_minValue');}var min = self._c('valueForKey_', '_minValue');self._c('customSlider')._c('setMinimumValue_',min);var callback = self._c('valueFormatter');if (callback) {self._c('minValueLabel')._c('setText_', callback(min));}}}, {});

**Comment by yangyangFeng** [comment]
可参照, name 属性声明
[https://github.com/yangyangFeng/TTPatch/blob/libffi/JS/src/Playground.js](url)

使用
`self.setName_("TTPatch");`
`Utils.log_info("当前name:" + self.name());`

**Comment by yangyangFeng** [comment]
> Fatal Exception: NSUnknownKeyException
> [<UIView 0x13f689e50> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key _minValue
> 
> 转义后代码：
> defineClass('TBSliderView', {setMaxValue_: function (maxValue) { self._c('setValue_forKey_', maxValue, '_maxValue'); if (isNaN(maxValue)) { var value = self._c('valueForKey_', '_value'); self._c('setValue_forKey_', value,'_maxValue');}var max = self._c('valueForKey_', '_maxValue');self._c('customSlider')._c('setMaximumValue_', max);var callback = self._c('valueFormatter');if (callback) {self._c('maxValueLabel')._c('setText_', callback(max));}},setMinValue_: function (minValue) {self._c('setValue_forKey_', minValue, '_minValue');if (isNaN(minValue)) {var value = self._c('valueForKey_', '_value');self._c('setValue_forKey_', value, '_minValue');}var min = self._c('valueForKey_', '_minValue');self._c('customSlider')._c('setMinimumValue_',min);var callback = self._c('valueFormatter');if (callback) {self._c('minValueLabel')._c('setText_', callback(min));}}}, {});

可参照, name 属性声明
[https://github.com/yangyangFeng/TTPatch/blob/libffi/JS/src/Playground.js](url)

使用
`self.setName_("TTPatch");`
`Utils.log_info("当前name:" + self.name());`
