### ISSUE TITLE
使用原生网络请求收不到回调

### ISSUE THREAD

**Issue by LuoPengFei** [yangyangFeng/TTPatch#21]
通过log可以看到数据请求发送，但是成功、失败均收不到回调

**Comment by yangyangFeng** [comment]
参照如下代码
`
      var url =
        "https://yangyangfeng.github.io/TTPatch_Convertor_Flutter/js/JPConvertor.js";
      var req = NSURLRequest.requestWithURL_(NSURL.URLWithString_(url));
      var dataTask = TTDFKitURLSession.dataTaskWithRequest_completionHandler_(
        req,
        block("void,id,id,id", function (data, response, error) {
          Utils.log_info(data);
        })
      );
      dataTask.resume();

`
