### ISSUE TITLE
请问一下，如何遵循代理以及实现代理呢？

### ISSUE THREAD

**Issue by maoweipengft** [yangyangFeng/TTPatch#7]
比如我想使用scrollview的滑动代理，应该怎么做呢？

**Comment by yangyangFeng** [comment]
替换当前scrollview.delegate 的协议方法即可

**Comment by yangyangFeng** [comment]
> 比如我想使用scrollview的滑动代理，应该怎么做呢？

https://github.com/yangyangFeng/TTPatch/wiki/%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95#3-defineclass
